# Introduction of Numpy

In [1]:
import numpy as np

In [2]:
arr=[1,2,3,4,5,6]

In [3]:
arr

[1, 2, 3, 4, 5, 6]

In [4]:
np.array(arr)

array([1, 2, 3, 4, 5, 6])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2=np.arange(1,12,2)
arr2

array([ 1,  3,  5,  7,  9, 11])

In [12]:
arr2.shape

(6,)

In [13]:

a=arr2.reshape(2,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [20]:
a.shape

(2, 3)

In [26]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [18]:
np.linspace(0,3,5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [24]:
np.eye(3,5,3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.random.rand(5,2)

array([[0.11874988, 0.01594501],
       [0.11135737, 0.93592462],
       [0.29993203, 0.30795296],
       [0.00693647, 0.19462829],
       [0.6975404 , 0.41637699]])

In [46]:
np.random.rand(5)

array([0.70248824, 0.4939255 , 0.14937493, 0.27630716, 0.67288381])

In [37]:
np.random.randint(2,20,4)

array([17, 12,  3, 12])

In [26]:
np.random.randint(5)

3

In [62]:
np.random.randint(1,10,3)

array([6, 3, 5])

In [63]:
np.random.randint(1,10,2)

array([8, 9])

In [64]:
arr4=np.arange(25)

In [65]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
ranarr=np.random.randint(1,25,25)

In [71]:
ranarr

array([ 9, 14,  1, 23, 20, 17, 24,  7,  3, 23, 17, 15,  4,  6, 10, 16,  5,
        5, 14, 15, 11,  5, 17, 21,  4])

In [74]:
arr4.shape

(25,)

In [76]:
new_arr4=arr4.reshape(5,5)

In [77]:
new_arr4.shape

(5, 5)

In [80]:
ranarr.min()

1

In [81]:
ranarr.max()

24

# Numpy Indexing and Selection

In [83]:
import numpy as  np

In [86]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr[5]

5

In [88]:
arr[1:4]

array([1, 2, 3])

**Boardcasting**

In [89]:
arr[0:3]=20

In [91]:
arr

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
slice_of_ar=arr[0:6]

In [95]:
slice_of_ar

array([0, 1, 2, 3, 4, 5])

In [96]:
slice_of_ar[:]=99

In [97]:
slice_of_ar

array([99, 99, 99, 99, 99, 99])

In [98]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [99]:
arr_copy=arr.copy()

In [100]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [138]:
arr_2d=np.array([[5,10,15,32],[20,25,30,22],[35,24,40,45],[22,18,4,54]])
arr_2d

array([[ 5, 10, 15, 32],
       [20, 25, 30, 22],
       [35, 24, 40, 45],
       [22, 18,  4, 54]])

In [157]:
arr_2d[:4,2:3]

array([[15],
       [30],
       [40],
       [ 4]])

Selection

In [158]:
arr=np.arange(1,11)

In [159]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [161]:
bool_arr=arr>5

In [162]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [163]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [168]:
arr1=np.arange(0,9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [169]:
arr1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [177]:
np.random.randint(0,9,9).reshape(3,3)

array([[3, 4, 3],
       [0, 2, 4],
       [7, 2, 4]])

In [178]:

mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [180]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [185]:
int(mat[3:4,4:5])

20

In [188]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [199]:
mat[:,]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [201]:
mat.sum()

325

In [198]:
mat.std()

7.211102550927978

In [202]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [203]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])